### ISSUE TITLE
message d'erreur depuis la mise a jour du 04/05/2023

### ISSUE THREAD

**Issue by albertus2023** [OGSteam/mod-attaques#25]
bonjour j'ai ce message d'erreur sur le mod attaque depuis que j'ai fait la mise a jours
merci de regarder ça 
bon courage.
![erreur mod attaque](https://user-images.githubusercontent.com/132708237/236553220-72f88230-7f65-4136-8f53-e16fc6f969bb.png)

**Comment by darknoon29** [comment]
@albertus2023 Il va falloir mettre à jour Autoupdate et prendre OGSPY 3.3.8. La RC2 devrait être la version définitive que je publierais en 3.3.8 la semaine prochaine.

**Comment by albertus2023** [comment]
@darknoon29  j'ai la version 3.2.2 pour autoupdate sur mon serveur et la 3.3.7 pour ogpsy tu me diras quand je pourrais mettre a jours.

**Comment by albertus2023** [comment]
Et voila passage a la version 3.3.8 et tout et rentré dans l'ordre, merci du boulot
